### ISSUE TITLE
Anonymous Blade Components

### ISSUE THREAD

**Issue by theutz** [Stillat/antlers-components#1]
First of all, AMAZING package, @JohnathonKoster! This will be such a huge boon to Statamic productivity!

But, secondly, I'm having trouble rendering a simple `<x-button>` anonymous component. When I create a component class, I have no issues. But when I delete the class, I get a `Class "components.button" does not exist` error. Any ideas how to make that work?

**Comment by JohnathonKoster** [comment]
Should be good to go after updating to `v1.0.1` 🙂

**Comment by theutz** [comment]
You, sir, are my hero. :)
