### ISSUE TITLE
Not sure if bug or feature

### ISSUE THREAD

**Issue by lokmanm** [Stillat/antlers-components#4]
Hey John, as always love your work!

We use this package heavily with our sites and just recently stumbled upon a thing but I am not sure if it's a bug or a feature.

I am trying to set the value of an alpine data based on the handle. In this case, the `handle` is the `antlers` value that I am trying to increase or decrease.

A blade component inside an antlers file for example:

field.antlers.html
```antlers
<x-button @click="{{ handle }}++">
  Submit
</x-button>
```
This will not work and the attribute is not evaluated at all. However, this does work:
```antlers
<x-button @click="{handle}++">
  Submit
</x-button>
```

Is it okay if we keep using the second option? Or do you think its a bug and the first one should work.

Thanks!

**Comment by JohnathonKoster** [comment]
The second option should always work - I'll do some reviews to verify though (and see what might be happening in the first example) 🙂

**Comment by lokmanm** [comment]
@JohnathonKoster thanks a lot!

On another note, this also does not work inside an antlers file:

```antlers
<x-input
    type="{input_type ?? 'text'}"
    name="{handle}"
    value="{value}"
    {{ js_attributes }}
/>
```
`js_attributes` is not being passed down to `x-input`. 

`x-input` is a Blade component that has the necessary styling. 

Am I missing anything? Thanks again.

**Comment by JohnathonKoster** [comment]
> @JohnathonKoster thanks a lot!
> 
> On another note, this also does not work inside an antlers file:
> 
> ```
> <x-input
>     type="{input_type ?? 'text'}"
>     name="{handle}"
>     value="{value}"
>     {{ js_attributes }}
> />
> ```
> 
> `js_attributes` is not being passed down to `x-input`.
> 
> `x-input` is a Blade component that has the necessary styling.
> 
> Am I missing anything? Thanks again.

I don't think parameters like that (`{{ js_attributes }}`) are currently supported. I'd have to dig to see what the variable names look like in the Core blade compiler to determine what _should_ happen there (and tons of edge cases to consider) - will give it a shot while reviewing the other items

**Comment by lokmanm** [comment]
@JohnathonKoster Ah sorry, I guess I hit some edge cases while tinkering. 

No worries though, I love the package so far! Copy-pasting `classes` will do for now.

**Comment by JohnathonKoster** [comment]
I've tagged version 2.1.0, which makes a few improvements here 🙂

The following will now compile to equivalent Antlers code behind the scenes:

```antlers
<x-button @click="{{ handle }}++">
  Submit
</x-button>

<x-button @click="{handle}++">
  Submit
</x-button>
```

In addition to that improvement, I've also added support for compiling arbitrary variable echos like this:

```antlers
<x-input
    type="{input_type ?? 'text'}"
    name="{handle}"
    value="{value}"
    {{ js_attributes }}
/>
```

The previous example would be equivalent to the following in regular Antlers:

```antlers
{{ tag_name :js_attributes="js_attributes" }}
```

If the input is more complicated like so:

```antlers
<x-input
    type="{input_type ?? 'text'}"
    name="{handle}"
    value="{value}"
    {{ js_attributes | upper }}
/>
```

it is equivalent to the following:

```antlers
{{ tag_name js_attributes="{js_attributes | upper}" }}
```

**Comment by lokmanm** [comment]
@JohnathonKoster thanks a lot 🍻
